name: flutter_boilerplate
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '2.19.2'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1
  flutter_mobx: ^2.0.6+5
  build_runner: ^2.3.3
  get: ^4.6.5
  get_it: ^7.2.0
  introduction_screen: ^3.1.0
  modal_bottom_sheet: ^2.1.2
  solid_bottom_sheet: ^0.1.10
  fancy_password_field: ^2.0.0
  card_swiper: ^2.0.4
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  smart_alert_dialog: ^4.0.4
  container_tab_indicator: ^0.3.0
  syncfusion_flutter_datepicker: ^20.4.38
  intl: ^0.17.0
  table_calendar: ^3.0.8
  super_tooltip: ^1.0.1
  google_fonts: ^3.0.1
  camera: ^0.10.1
  masked_text_field: ^1.0.1
  extended_masked_text: ^2.3.1
  flutter_animated_dialog: ^2.0.1
  show_more_text_popup: ^0.3.0
  fluttertoast: ^8.1.2
  animated_dialog_box: ^0.0.2
  syncfusion_flutter_pdf: ^20.4.43
  path_provider: ^2.0.11
  open_file: ^3.2.1
  tckn_check: ^0.0.4
  email_validator: ^2.1.17
  flutter_bounceable: ^1.1.0



assets:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/languages/
  fonts:
      - family: Raleway_ExtraLight
        fonts:
          - asset: assets/fonts/Raleway_ExtraLight.ttf
      - family: Roboto-Thin
        fonts:
          - asset: assets/fonts/Roboto-Thin.ttf